//COMMON

//GET TRAVIAS QUIZES
export const GET_YOUR_QUIZES = "GET_YOUR_QUIZES";
export const ACTIVE_ALL_QUIZES = "ACTIVE_ALL_QUIZES";
export const ACTIVE_YOUR_QUIZES = "ACTIVE_YOUR_QUIZES";
export const ACTIVE_TRAVIAS_QUIZES = "ACTIVE_TRAVIAS_QUIZES";

//GET TRAVIAS QUIZES
export const GET_TRAVIAS_QUIZES = "GET_TRAVIAS_QUIZES";

export const GET_QUIZ = "GET_QUIZ";

export const ADD_QUIZ_INFORMATION = "ADD_QUIZ_INFORMATION";
export const ADD_QUIZ_QUESTION = "ADD_QUIZ_QUESTION";
export const SAVE_QUIZ = "SAVE_QUIZ";
export const PREVIOUS_QUESTION = "PREVIOUS_QUESTION";
export const PREVIOUS_QUIZ_INFORMATION = "PREVIOUS_QUIZ_INFORMATION";
export const SET_CLEAR_CREATE_QUIZ = "SET_CLEAR_CREATE_QUIZ";

export const CHANGE_CREATE_QUIZ_TITLE = "CHANGE_CREATE_QUIZ_TITLE";
export const CHANGE_CREATE_QUIZ_DESCRIPTION = "CHANGE_CREATE_QUIZ_DESCRIPTION";
export const CHANGE_CREATE_QUIZ_CATEGORY = "CHANGE_CREATE_QUIZ_CATEGORY";
export const CHANGE_CREATE_QUIZ_TYPE = "CHANGE_CREATE_QUIZ_TYPE";
export const CHANGE_CREATE_QUIZ_DIFFICULTY = "CHANGE_CREATE_QUIZ_DIFFICULTY";

export const ADD_NEW_ANSWER = "ADD_NEW_ANSWER";
export const TRUE_OR_FALSE_ACTION = "TRUE_OR_FALSE_ACTION";
export const SET_QUESTION = "SET_QUESTION";
export const SET_ANSWER = "SET_ANSWER";
export const CLEAR_VALUES = "CLEAR_VALUES";
export const SEND_ERROR = "SEND_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

/*

export const GET_CONTACTS = "GET_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";
export const CONTACT_ERROR = "CONTACT_ERROR";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const FILTER_CONTACTS = "FILTER_CONTACTS";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

*/
