//COMMON
export const SET_VALID_QUIZES = "SET_VALID_QUIZES";
export const SEARCH_QUIZES = "SEARCH_QUIZES";
export const SORT_YOUR_QUIZES_BY_DATE = "SORT_YOUR_QUIZES_BY_DATE";
export const SORT_YOUR_QUIZES_BY_TITLE = "SORT_YOUR_QUIZES_BY_TITLE";
export const SORT_YOUR_QUIZES_BY_QUESTION = "SORT_YOUR_QUIZES_BY_QUESTION";

//GET TRAVIAS QUIZES
export const GET_YOUR_QUIZES = "GET_YOUR_QUIZES";
export const ACTIVE_ALL_QUIZES = "ACTIVE_ALL_QUIZES";
export const ACTIVE_YOUR_QUIZES = "ACTIVE_YOUR_QUIZES";
export const ACTIVE_TRAVIAS_QUIZES = "ACTIVE_TRAVIAS_QUIZES";

//GET TRAVIAS QUIZES
export const GET_TRAVIAS_QUIZES = "GET_TRAVIAS_QUIZES";

export const GET_QUIZ = "GET_QUIZ";

export const ADD_QUIZ_INFORMATION = "ADD_QUIZ_INFORMATION";
export const ADD_QUIZ_QUESTION = "ADD_QUIZ_QUESTION";
export const SAVE_QUIZ = "SAVE_QUIZ";
export const PREVIOUS_QUESTION = "PREVIOUS_QUESTION";
export const PREVIOUS_QUIZ_INFORMATION = "PREVIOUS_QUIZ_INFORMATION";
export const SET_CLEAR_CREATE_QUIZ = "SET_CLEAR_CREATE_QUIZ";

export const CHANGE_CREATE_QUIZ_TITLE = "CHANGE_CREATE_QUIZ_TITLE";
export const CHANGE_CREATE_QUIZ_DESCRIPTION = "CHANGE_CREATE_QUIZ_DESCRIPTION";
export const CHANGE_CREATE_QUIZ_CATEGORY = "CHANGE_CREATE_QUIZ_CATEGORY";
export const CHANGE_CREATE_QUIZ_TYPE = "CHANGE_CREATE_QUIZ_TYPE";
export const CHANGE_CREATE_QUIZ_DIFFICULTY = "CHANGE_CREATE_QUIZ_DIFFICULTY";

export const ADD_NEW_ANSWER = "ADD_NEW_ANSWER";
export const TRUE_OR_FALSE_ACTION = "TRUE_OR_FALSE_ACTION";
export const SET_QUESTION = "SET_QUESTION";
export const SET_ANSWER = "SET_ANSWER";
export const CLEAR_VALUES = "CLEAR_VALUES";
export const SEND_ERROR = "SEND_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

//REGISTRATION
export const SET_LOGIN_ACTIVE = "SET_LOGIN_ACTIVE";
export const SET_REGISTER_ACTIVE = "SET_REGISTER_ACTIVE";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//USERS
export const GET_USERS = "GET_USERS";
