//CREATE
export const ACTION_ADD_NEW_ANSWER = "ACTION_ADD_NEW_ANSWER";
export const ACTION_ADD_QUIZ_INFORMATION = "ACTION_ADD_QUIZ_INFORMATION";
export const ACTION_ADD_QUIZ_QUESTION = "ACTION_ADD_QUIZ_QUESTION";
export const ACTION_CLEAR_ERROR = "ACTION_CLEAR_ERROR";
export const ACTION_CLEAR_VALUES = "ACTION_CLEAR_VALUES";
export const ACTION_CHANGE_CREATE_QUIZ_CATEGORY =
  "ACTION_CHANGE_CREATE_QUIZ_CATEGORY";
export const ACTION_CHANGE_CREATE_QUIZ_DESCRIPTION =
  "ACTION_CHANGE_CREATE_QUIZ_DESCRIPTION";
export const ACTION_CHANGE_CREATE_QUIZ_DIFFICULTY =
  "ACTION_CHANGE_CREATE_QUIZ_DIFFICULTY";
export const ACTION_CHANGE_CREATE_QUIZ_TITLE =
  "ACTION_CHANGE_CREATE_QUIZ_TITLE";
export const ACTION_CHANGE_CREATE_QUIZ_TYPE = "ACTION_CHANGE_CREATE_QUIZ_TYPE";
export const ACTION_GET_IMAGE_INFORMATION = "ACTION_GET_IMAGE_INFORMATION";
export const ACTION_PREVIOUS_QUESTION = "ACTION_PREVIOUS_QUESTION";
export const ACTION_PREVIOUS_QUIZ_INFORMATION =
  "ACTION_PREVIOUS_QUIZ_INFORMATION";
export const ACTION_SAVE_QUIZ = "ACTION_SAVE_QUIZ";
export const ACTION_SEND_ERROR = "ACTION_SEND_ERROR";
export const ACTION_SET_ANSWER = "ACTION_SET_ANSWER";
export const ACTION_SET_CLEAR_CREATE_QUIZ = "ACTION_SET_CLEAR_CREATE_QUIZ";
export const ACTION_SET_QUESTION = "ACTION_SET_QUESTION";
export const ACTION_TRUE_OR_FALSE_ACTION = "ACTION_TRUE_OR_FALSE_ACTION";

//QUIZ
export const ACTION_GET_QUIZES = "ACTION_GET_QUIZES";
export const ACTION_GET_USER_QUIZES = "ACTION_GET_USER_QUIZES";
export const ACTION_GET_QUIZ_SCOREBOARD = "ACTION_GET_QUIZ_SCOREBOARD";
export const ACTION_SEARCH_QUIZES = "ACTION_SEARCH_QUIZES";
export const ACTION_SET_QUIZ_DIFFICUTY = "ACTION_SET_QUIZ_DIFFICUTY";
export const ACTION_SET_VALID_QUIZES = "ACTION_SET_VALID_QUIZES";
export const ACTION_SORT_QUIZES = "ACTION_SORT_QUIZES";

//USERS
export const ACTION_AUTH_ERROR = "ACTION_AUTH_ERROR";
export const ACTION_CLEAR_ERRORS = "ACTION_CLEAR_ERRORS";
export const ACTION_GET_USERS = "ACTION_GET_USERS";
export const ACTION_LOGIN_FAIL = "ACTION_LOGIN_FAIL";
export const ACTION_LOGIN_SUCCESS = "ACTION_LOGIN_SUCCESS";
export const ACTION_LOGOUT = "ACTION_LOGOUT";
export const ACTION_REGISTER_FAIL = "ACTION_REGISTER_FAIL";
export const ACTION_REGISTER_SUCCESS = "ACTION_REGISTER_SUCCESS";
export const ACTION_SET_LOGIN_ACTIVE = "ACTION_SET_LOGIN_ACTIVE";
export const ACTION_SET_REGISTER_ACTIVE = "ACTION_SET_REGISTER_ACTIVE";
export const ACTION_USER_LOADED = "ACTION_USER_LOADED";
